# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bxJBUJCMLgfkaL9pH1qs9C4s8tGVP6Zg
"""

import streamlit as st
from transformers import GPT2Tokenizer, GPT2LMHeadModel
import torch

# Load model and tokenizer
@st.cache_resource
def load_model():
    tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
    model = GPT2LMHeadModel.from_pretrained('gpt2')
    model.eval()
    return tokenizer, model

tokenizer, model = load_model()

# Predict next full sentence
def predict_next_sentences(prompt, num_return_sequences=3):
    inputs = tokenizer(prompt, return_tensors="pt")

    outputs = model.generate(
        **inputs,
        max_length=inputs["input_ids"].shape[1] + 30,
        num_return_sequences=num_return_sequences,
        do_sample=True,
        top_k=50,
        top_p=0.95,
        temperature=0.9,
        pad_token_id=tokenizer.eos_token_id
    )

    predictions = []
    for output in outputs:
        decoded = tokenizer.decode(output, skip_special_tokens=True)
        continuation = decoded[len(prompt):].strip()
        # Extract the first sentence after the prompt
        sentence = continuation.split(".")[0].strip() + "."
        if sentence != ".":
            predictions.append(sentence)

    return list(dict.fromkeys(predictions))  # Remove duplicates

# --- Streamlit UI ---
st.set_page_config(page_title="Next Sentence Predictor", page_icon="📝")
st.title("📝 Next Sentence Predictor using GPT-2")
st.markdown("Enter the beginning of a sentence, and the model will generate possible **next full sentences**.")

prompt = st.text_input("Enter your sentence:")

if prompt:
    predictions = predict_next_sentences(prompt)
    st.subheader("📘 Predicted Next Sentences:")
    for i, sentence in enumerate(predictions, 1):
        st.write(f"{i}. {sentence}")